
fastlane_version "2.105.2"

default_platform :ios

platform :ios do

  desc "Run unit tests and check library"
  lane :test do
    scan(workspace: "Randient.xcworkspace", scheme: "Randient", clean: true)
    pod_lib_lint
  end

  desc "Publish a new version to CocoaPods and GitHub"
  lane :publish do
    test

    podspec = "Randient.podspec"
    version = version_get_podspec(path: podspec)

    # Push new Github release
    github_release = set_github_release(
      repository_name: "uias/Randient",
      api_token: ENV["GITHUB_TOKEN"],
      name: version,
      tag_name: version,
      description: "#{version} release.",
      commitish: "master"
    )

    # Push spec
    pod_push(allow_warnings: true, verbose: true)

    slack(
      message: "Pageboy v#{version} released!" 
    )
  end
end