
fastlane_version "2.26.1"

default_platform :ios

platform :ios do

  desc "Run unit tests and check library"
  lane :test do
    scan(workspace: "Tabman.xcworkspace", scheme: "Tabman", clean: true)
  end

  desc "Deploy a new version to CocoaPods and GitHub"
  lane :deploy do
    test

    # Compose .xcconfig file path
    configuration = Xcodeproj::Config.new("../Tabman.xcconfig")
    version = configuration.attributes['TM_VERSION']

    # Push new Github release
    github_release = set_github_release(
      repository_name: "uias/Tabman",
      api_token: ENV["GITHUB_API_TOKEN"],
      name: version,
      tag_name: version,
      description: "#{version} release.",
      commitish: "main"
    )

    slack(
      message: "Tabman v#{version} released!" 
    )
  end
end